//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Assignment
    {
        public int AssignmentID { get; set; }
        public int EventID { get; set; }
        public int VolunteerID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
